networks:
  default:
    name: magalu-cloud-terraform
    driver: bridge

services:
  backend:
    image: deirofelippe/magalucloud-terraform:v1.1
    container_name: backend
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - ./.env
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
      interval: 5s
      retries: 5
      timeout: 5s
      start_period: 30s
      start_interval: 5s

  database:
    image: postgres:17.1-bookworm
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./.pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: lancamentos
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 3s
      retries: 10
      timeout: 5s
      start_period: 30s
      start_interval: 5s
