networks:
  default:
    name: magalu-cloud-terraform
    driver: bridge

services:
  backend:
    image: deirofelippe/magalu-cloud-terraform:latest
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: backend
    volumes:
      - "./:/home/py/app"
    ports:
      - "3000:3000"
    restart: always
    command: sleep inf
    env_file:
      - ./.env
    depends_on:
      database:
        condition: service_healthy
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3000/healthz"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    #   start_period: 30s
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M

  database:
    image: postgres:17.1-bookworm
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: lancamentos
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 3s
      timeout: 5s
      retries: 10

  pgadmin:
    image: elestio/pgadmin:REL-8_13
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 8080
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8080:8080"
